# Generated by Django 2.2 on 2021-05-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resize_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelimage',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
