# Generated by Django 2.2 on 2021-05-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_resize_images', '0002_auto_20210506_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelimage',
            name='name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
